### ISSUE TITLE
What is the reason for the abs() in this line of code?

### ISSUE THREAD

**Issue by jeremy9959** [RabadanLab/randomly#1]
In the ```refining``` computation, you project the genes into the random eigenspaces in order to identify those whose components differ from a normal distribution by a lot.   Why do you take the absolute value of the eigenvector components?

https://github.com/RabadanLab/randomly/blob/7961402fbf3587d502336444a0eae4192cc076db/randomly/randomly.py#L808

**Comment by luisaparicio** [comment]
Hi Jeremy,

Thanks for your interest and sorry for our delay in replaying. As you comment on your question, the idea is to project in a random space to study the behavior of each gene. We take advantage of the randomized data eigenvectors (which are a basis of a random space) but in principle, we could have generated a basis of orthonormal vectors and project the genes in such space. As you can imagine, the bigger in the dimension of the random space, the better you are able to test the gaussianity of the projected genes. 

One way of testing how good or bad is the dimension of your random space for this purpose is to check if the genes with very low expression are highly non-gaussian. For example, a gene expressed in, say, three cells, once projected should not behave like a gaussian, because with such small number of points  (cells) there is no way of saying that is normally distributed. We realized that if one projects on the eigenvectors of the randomized data, we obtain a lot of false positives. In particular some genes with almost no expression where tested as gaussian. A possible solution would be to generate a much bigger random space, but this is computationally very expensive. Instead of this, one can restrict the vectors to a certain hyper-sphere by projecting them into positive components and hence the resulting space is more dense in number of vectors, and the projection looks much better. You can think this as if you were projecting in a sector  (well sampled)  of a hyper-sphere instead of projecting in the whole (but badly sampled) hyper-sphere. With this trick, very low expressed genes are always non-gaussian and highly expressed genes (which by definition are much less affected by dropout and hence less bimodal) are always gaussian, which is the behavior one should expect .

**Comment by jeremy9959** [comment]
Thanks, this is a very interesting idea that definitely had not occurred to me.  Taking the absolute values of the eigenvector components seemed an odd thing to do, but this makes sense.

**Comment by jeremy9959** [comment]
Dear Luis,

If you don’t mind, I have another question for you about your paper.  I have not been able to figure out how to reproduce figure 1C,
In particular the left bar in each pair.  What are you counting to obtain the fraction of biological signal vs sparsity vs noise?
I imagine the noise % are the eigenvalues that fit the MP distribution.  How do you divide the rest? Or am I wildly off track?

Thanks,
Jeremy


--
Jeremy Teitelbaum
Visiting Scientist, JAX-GM
Professor of Mathematics
Department of Mathematics U-1009
University of Connecticut
Storrs, CT 06269-1009
http://teitelbaum.math.uconn.edu
